<template>
  <div class="001">
    <h1>002</h1>
    <h2>Even Fibonacci numbers</h2>
    <br />
    <p>
      Each new term in the Fibonacci sequence is generated by adding the
      previous two terms. By starting with 1 and 2, the first 10 terms will be:
    </p>
    <p>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
    <p>
      By considering the terms in the Fibonacci sequence whose values do not
      exceed four million, find the sum of the even-valued terms.
    </p>

    <v-form ref="form">
      <v-text-field
        label="Limit"
        v-model.lazy="limit"
        prepend-icon="mdi-format-vertical-align-top"
        outlined
      ></v-text-field>
      <v-text-field
        label="Divider"
        v-model.lazy="divider"
        prepend-icon="mdi-numeric-1-box-outline"
        outlined
      ></v-text-field>
      <v-text-field
        label="Result"
        v-model="result"
        prepend-icon="mdi-subdirectory-arrow-right"
        outlined
        readonly
      ></v-text-field>
    </v-form>
  </div>
</template>

<script>
export default {
  data() {
    return {
      divider: 2,
      limit: 4000000,
    };
  },
  computed: {
    result() {
      let fibonacci = [1, 2];
      let divided_fibonacci = [];
      let divider2 = this.divider;

      if (fibonacci[0] % divider2 === 0) {
        divided_fibonacci.push(fibonacci[0]);
      }

      if (fibonacci[1] % divider2 === 0) {
        divided_fibonacci.push(fibonacci[1]);
      }

      while (fibonacci[fibonacci.length - 1] <= this.limit) {
        fibonacci.push(
          fibonacci[fibonacci.length - 1] + fibonacci[fibonacci.length - 2]
        );
        if (fibonacci[fibonacci.length - 1] % this.divider === 0) {
          divided_fibonacci.push(fibonacci[fibonacci.length - 1]);
        }
      }

      if (divided_fibonacci[divided_fibonacci.length - 1] >= this.limit) {
        divided_fibonacci.pop();
      }

      return divided_fibonacci.reduce((pv, cv) => pv + cv, 0);
    },
  },
};
</script>

<style scoped></style>
